### ISSUE TITLE
Can it be integrated in object detection framework like yolov4/v5?

### ISSUE THREAD

**Issue by williamhyin** [alldbi/SuperMix#4]
HI 

Thanks for your great work. I hope to use your supermix technology in object detection framework like yolov4/v5.
How can i integrated it efficiently in this framework?

**Comment by jsrdcht** [comment]
same question,how to use it in object detection?

**Comment by alldbi** [comment]
Hi, 

I am glad that you are interested in our work. 

For improving object detection, since bounding boxes are available, you can just cut objects and past them on the other image and add the new bounding box information to the corresponding annotation. Then train the model on this dataset and see how much improvement can be achieved. Afterward, to further enhance the performance of mixing, you can mix images using SuperMix and then combine bounding box information according to the mixing masks estimated by SuperMix. For instance, if the mixing mask for one image has overlap with the bounding box of an object in that image, you can simply consider that bounding box as a valid bounding box for the mixed image. 

Thanks, 
Ali
